"""Model families used in controlled Q-Neuro comparisons."""

from qneuro.models.advanced import (
    ComplexEvidenceAccumulator,
    ComplexEvidenceMLP,
    CoupledTensorState,
    DiagnosticDensityDynamics,
    DiagonalStateSpace,
    EnergyAttractorState,
    EvidenceGraphNetwork,
    HamiltonianDissipativeState,
    LogisticEvidence,
    ModernHopfieldMemory,
    RealEvidenceAccumulator,
)
from qneuro.models.baselines import (
    CausalTransformer,
    DenseRealMatrixRecurrence,
    EvidenceMLP,
    OrthogonalRealRecurrence,
    ResidualGatedRecurrent,
    TinyGRU,
    TinyLSTM,
    TinyRNN,
    TinyTransformer,
)
from qneuro.models.equivalent import (
    ExactRealBlockOperatorState,
    RealPolarOperatorState,
    RealRotationBlockOperator,
)
from qneuro.models.mechanisms import (
    AmbiguityAwareComplexOperator,
    AmbiguityAwareRealOperator,
    CommutatorPenaltyComplexOperator,
    CommutingComplexOperatorState,
    FixedRandomComplexOperator,
    FixedTwoStateAttractor,
    FrozenReadoutComplexOperator,
    MagnitudeDestroyedOperator,
    NoConjugationComplexOperator,
    NoncommutativeRealOperator,
    PhaseDestroyedTrainingOperator,
)
from qneuro.models.operators import (
    ComplexMagnitudeReadoutOperator,
    ComplexNoNegativeEvidenceOperator,
    ComplexOperatorState,
    RealOperatorState,
    TwoChannelRealOperatorState,
)

__all__ = [
    "AmbiguityAwareComplexOperator",
    "AmbiguityAwareRealOperator",
    "CausalTransformer",
    "CommutatorPenaltyComplexOperator",
    "CommutingComplexOperatorState",
    "ComplexEvidenceAccumulator",
    "ComplexEvidenceMLP",
    "ComplexMagnitudeReadoutOperator",
    "ComplexNoNegativeEvidenceOperator",
    "ComplexOperatorState",
    "CoupledTensorState",
    "DenseRealMatrixRecurrence",
    "DiagnosticDensityDynamics",
    "DiagonalStateSpace",
    "EnergyAttractorState",
    "EvidenceGraphNetwork",
    "EvidenceMLP",
    "ExactRealBlockOperatorState",
    "FixedRandomComplexOperator",
    "FixedTwoStateAttractor",
    "FrozenReadoutComplexOperator",
    "HamiltonianDissipativeState",
    "LogisticEvidence",
    "MagnitudeDestroyedOperator",
    "ModernHopfieldMemory",
    "NoConjugationComplexOperator",
    "NoncommutativeRealOperator",
    "OrthogonalRealRecurrence",
    "PhaseDestroyedTrainingOperator",
    "RealEvidenceAccumulator",
    "RealOperatorState",
    "RealPolarOperatorState",
    "RealRotationBlockOperator",
    "ResidualGatedRecurrent",
    "TinyGRU",
    "TinyLSTM",
    "TinyRNN",
    "TinyTransformer",
    "TwoChannelRealOperatorState",
]
