"""Diagnostic task suite: eight algorithmic problems, each with a length-extrapolation split.

Every task has a known optimal procedure, so a model either implements the procedure or it does
not. That is deliberately a harsher instrument than a benchmark score: it makes the difference
between "learned the algorithm" and "fitted the training lengths" directly measurable, by testing
at lengths never trained on.

Length extrapolation is chosen as the primary axis because it is a **systematic** failure of the
dominant architectures rather than a matter of tuning. A method that extrapolates where
transformers, gated RNNs and state-space models collapse would be a capability difference, not a
benchmark tick.

Uniform interface so every model in the zoo sees identical data:

    x    (B, L) int64 tokens
    y    (B, L) int64 targets
    mask (B, L) bool  -- positions that are scored

Tasks differ in what computation the target requires:

===================  ==========================================================
parity_scan          running state, unbounded accumulation
mod_sum              running state, modular arithmetic
cummax               running state, order statistics
dyck_depth           counter / stack depth
copy                 verbatim memory over a delay
reverse              memory plus order inversion
sort                 global comparison, not expressible as a scan
needle               content-addressed retrieval
===================  ==========================================================
"""

from __future__ import annotations

from collections.abc import Callable

import torch

#: Reserved tokens shared by every task, so a single embedding table serves all of them.
PAD, SEP, BLANK = 0, 1, 2
FIRST = 3


def _empty(batch: int, length: int) -> dict[str, torch.Tensor]:
    return {
        "x": torch.full((batch, length), PAD, dtype=torch.long),
        "y": torch.full((batch, length), PAD, dtype=torch.long),
        "mask": torch.zeros(batch, length, dtype=torch.bool),
    }


def parity_scan(batch: int, length: int, *, generator: torch.Generator, **_) -> dict:
    """y[i] = parity of x[:i+1]. Requires a persistent one-bit state over the whole prefix."""

    out = _empty(batch, length)
    bits = torch.randint(0, 2, (batch, length), generator=generator)
    out["x"] = bits + FIRST
    out["y"] = (bits.cumsum(1) % 2) + FIRST
    out["mask"][:] = True
    return out


def mod_sum(batch: int, length: int, *, generator: torch.Generator, modulus: int = 7, **_) -> dict:
    """y[i] = (sum of x[:i+1]) mod m. Parity's arithmetic generalisation."""

    out = _empty(batch, length)
    values = torch.randint(0, modulus, (batch, length), generator=generator)
    out["x"] = values + FIRST
    out["y"] = (values.cumsum(1) % modulus) + FIRST
    out["mask"][:] = True
    return out


def cummax(batch: int, length: int, *, generator: torch.Generator, values: int = 8, **_) -> dict:
    """y[i] = max(x[:i+1]). A scan whose state is an order statistic rather than a sum."""

    out = _empty(batch, length)
    symbols = torch.randint(0, values, (batch, length), generator=generator)
    out["x"] = symbols + FIRST
    out["y"] = symbols.cummax(1).values + FIRST
    out["mask"][:] = True
    return out


def dyck_depth(batch: int, length: int, *, generator: torch.Generator, cap: int = 8, **_) -> dict:
    """y[i] = bracket nesting depth after x[:i+1], clipped. A counter that must never go negative.

    Sequences are generated by a random walk that is reflected at zero, so the depth is a genuine
    stack height rather than a balanced-bracket string with a trivial global answer.
    """

    out = _empty(batch, length)
    steps = torch.randint(0, 2, (batch, length), generator=generator) * 2 - 1
    depth = torch.zeros(batch, dtype=torch.long)
    tokens, depths = [], []
    for index in range(length):
        step = steps[:, index]
        step = torch.where(depth <= 0, torch.ones_like(step), step)
        depth = (depth + step).clamp(0, cap)
        tokens.append((step > 0).long())
        depths.append(depth.clone())
    out["x"] = torch.stack(tokens, 1) + FIRST
    out["y"] = torch.stack(depths, 1) + FIRST
    out["mask"][:] = True
    return out


def _delayed(batch: int, length: int, generator: torch.Generator, symbols: int, reverse: bool):
    """Shared layout for copy/reverse: payload, separator, then the answer region."""

    out = _empty(batch, length)
    half = (length - 1) // 2
    payload = torch.randint(0, symbols, (batch, half), generator=generator) + FIRST
    out["x"][:, :half] = payload
    out["x"][:, half] = SEP
    out["x"][:, half + 1 :] = BLANK
    answer = payload.flip(1) if reverse else payload
    out["y"][:, half + 1 : half + 1 + half] = answer
    out["mask"][:, half + 1 : half + 1 + half] = True
    return out


def copy(batch: int, length: int, *, generator: torch.Generator, symbols: int = 8, **_) -> dict:
    """Reproduce the payload after a separator. Pure memory over a growing delay."""

    return _delayed(batch, length, generator, symbols, reverse=False)


def reverse(batch: int, length: int, *, generator: torch.Generator, symbols: int = 8, **_) -> dict:
    """Reproduce the payload backwards: memory plus an order inversion."""

    return _delayed(batch, length, generator, symbols, reverse=True)


def sort(batch: int, length: int, *, generator: torch.Generator, symbols: int = 8, **_) -> dict:
    """Emit the payload in sorted order. Not expressible as a left-to-right scan."""

    out = _empty(batch, length)
    half = (length - 1) // 2
    payload = torch.randint(0, symbols, (batch, half), generator=generator)
    out["x"][:, :half] = payload + FIRST
    out["x"][:, half] = SEP
    out["x"][:, half + 1 :] = BLANK
    out["y"][:, half + 1 : half + 1 + half] = payload.sort(1).values + FIRST
    out["mask"][:, half + 1 : half + 1 + half] = True
    return out


def needle(batch: int, length: int, *, generator: torch.Generator, symbols: int = 8, **_) -> dict:
    """Key-value pairs, then a query key; emit the matching value. Associative retrieval.

    Keys are unique within an example, so the answer is well defined and cannot be guessed from
    position.
    """

    out = _empty(batch, length)
    # Keys must stay unique within an example for the answer to be well defined, so the number of
    # pairs cannot exceed the symbol pool. At long evaluation lengths the remainder is padding,
    # which makes the retrieval delay longer rather than the task easier.
    pairs = max(1, min((length - 3) // 2, symbols))
    keys = torch.stack(
        [torch.randperm(symbols, generator=generator)[:pairs] for _ in range(batch)]
    )
    values = torch.randint(0, symbols, (batch, pairs), generator=generator)
    interleaved = torch.stack([keys, values], dim=2).reshape(batch, 2 * pairs)
    out["x"][:, : 2 * pairs] = interleaved + FIRST
    out["x"][:, 2 * pairs :] = BLANK
    choice = torch.randint(0, pairs, (batch,), generator=generator)
    # The query sits at the very end, so the retrieval distance grows with the evaluation length.
    out["x"][:, length - 2] = SEP
    out["x"][:, length - 1] = keys.gather(1, choice.unsqueeze(1)).squeeze(1) + FIRST
    out["y"][:, length - 1] = values.gather(1, choice.unsqueeze(1)).squeeze(1) + FIRST
    out["mask"][:, length - 1] = True
    return out


TASKS: dict[str, Callable[..., dict]] = {
    "parity_scan": parity_scan,
    "mod_sum": mod_sum,
    "cummax": cummax,
    "dyck_depth": dyck_depth,
    "copy": copy,
    "reverse": reverse,
    "sort": sort,
    "needle": needle,
}

#: Vocabulary large enough for every task's symbols plus the three reserved tokens.
VOCAB = FIRST + 16

#: Lengths a model trains on, and the lengths it is tested at. Anything beyond `TRAIN_MAX` was
#: never seen, so accuracy there measures whether the procedure generalises rather than whether the
#: training lengths were fitted.
TRAIN_MIN, TRAIN_MAX = 8, 16
EVAL_LENGTHS = (16, 32, 64)


def make(
    name: str, batch: int, length: int, *, seed: int, **options
) -> dict[str, torch.Tensor]:
    generator = torch.Generator().manual_seed(seed)
    return TASKS[name](batch, length, generator=generator, **options)


def train_batch(name: str, batch: int, *, seed: int, **options) -> dict[str, torch.Tensor]:
    """A training batch at a length sampled from the training range.

    Padding to `TRAIN_MAX` keeps tensor shapes constant so the harness can compare architectures
    without shape-dependent overheads confounding the timing.
    """

    generator = torch.Generator().manual_seed(seed)
    length = int(torch.randint(TRAIN_MIN, TRAIN_MAX + 1, (1,), generator=generator))
    sample = TASKS[name](batch, length, generator=generator, **options)
    if length == TRAIN_MAX:
        return sample
    pad = TRAIN_MAX - length
    return {
        "x": torch.nn.functional.pad(sample["x"], (0, pad), value=PAD),
        "y": torch.nn.functional.pad(sample["y"], (0, pad), value=PAD),
        "mask": torch.nn.functional.pad(sample["mask"], (0, pad), value=False),
    }


def chance_level(name: str) -> float:
    """Accuracy a model achieves by always emitting the most common target. The bar to clear."""

    sample = make(name, 4096, TRAIN_MAX, seed=12345)
    targets = sample["y"][sample["mask"]]
    if targets.numel() == 0:
        return 0.0
    return float(torch.bincount(targets).max()) / targets.numel()
